import { Era, HistoricalEvent, Side } from './types';

export const EVENTS: HistoricalEvent[] = [
  {
    id: '1840-opium-war',
    year: '1840',
    dateStr: '1840.6',
    title: '鸦片战争',
    description: '英国以虎门销烟为借口发动侵华战争，清政府战败，被迫签订《南京条约》，中国开始沦为半殖民地半封建社会。',
    people: '林则徐、道光帝',
    meaning: '中国近代史的开端，民族危机全面显现。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
    isMajor: true,
  },
  {
    id: '1851-taiping',
    year: '1851-1864',
    dateStr: '1851.1',
    title: '太平天国运动',
    description: '洪秀全在金田起义，建立太平天国，沉重打击了清王朝统治和外国侵略势力。',
    people: '洪秀全、杨秀清',
    meaning: '近代中国规模空前的农民战争，推动清政府统治体系进一步瓦解。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1856-second-opium-war',
    year: '1856-1860',
    dateStr: '1856.10',
    title: '第二次鸦片战争',
    description: '英法联军借亚罗号事件发动侵华战争并攻陷北京，清政府被迫签订《天津条约》《北京条约》。',
    people: '咸丰帝、英法联军',
    meaning: '中国半殖民地化程度进一步加深，主权进一步丧失。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1861-self-strengthening',
    year: '1861-1894',
    dateStr: '1861.1',
    title: '洋务运动',
    description: '清政府内部洋务派以“自强”“求富”为口号，引进西方军事工业、民用工业和近代教育。',
    people: '曾国藩、李鸿章、左宗棠',
    meaning: '中国近代化的早期开端，但未能改变旧制度的根本困局。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1894-jiawu',
    year: '1894-1895',
    dateStr: '1894.7',
    title: '甲午中日战争',
    description: '日本发动侵华战争，清军和北洋水师接连失利，清政府被迫签订《马关条约》。',
    people: '李鸿章、丁汝昌',
    meaning: '宣告洋务运动破产，列强瓜分中国危机急剧加深。',
    side: Side.JAPAN,
    era: Era.OLD_DEMOCRATIC,
    isMajor: true,
  },
  {
    id: '1895-gongche',
    year: '1895',
    dateStr: '1895.5',
    title: '公车上书',
    description: '康有为、梁启超等联名上书，要求拒和、迁都、变法，维新运动开始形成全国性政治声势。',
    people: '康有为、梁启超',
    meaning: '资产阶级维新派登上历史舞台，救亡图存要求进一步高涨。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1898-reform',
    year: '1898',
    dateStr: '1898.6',
    title: '戊戌变法',
    description: '维新派在光绪帝支持下推行政治改革，但仅持续百余天便被顽固势力镇压。',
    people: '康有为、梁启超、光绪帝',
    meaning: '说明在旧制度框架内走改良道路难以救国。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1900-boxer-war',
    year: '1900',
    dateStr: '1900.6',
    title: '八国联军侵华',
    description: '八国联军攻陷北京，清政府被迫签订《辛丑条约》，赔款巨额，主权严重受损。',
    people: '慈禧太后、八国联军',
    meaning: '民族危机空前加深，社会各阶层寻求新的救国道路。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
    isMajor: true,
  },
  {
    id: '1901-new-policy',
    year: '1901',
    dateStr: '1901.1',
    title: '清末新政',
    description: '清政府在内外压力下推行新政，涉及军事、教育、官制等方面，但改革力度有限。',
    people: '清政府统治集团',
    meaning: '反映清王朝统治危机加剧，但无法挽救其覆亡命运。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1906-constitutional-prep',
    year: '1906-1911',
    dateStr: '1906.9',
    title: '预备立宪',
    description: '清政府宣布“预备仿行宪政”，但始终试图维持专制统治，未能回应社会变革要求。',
    people: '清政府统治集团',
    meaning: '进一步暴露清王朝改革的虚伪性，加速革命形势发展。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1911-xinhai',
    year: '1911',
    dateStr: '1911.10',
    title: '辛亥革命',
    description: '武昌起义后全国响应，清帝退位，中华民国成立，延续数千年的君主专制制度被推翻。',
    people: '孙中山、黄兴',
    meaning: '建立了亚洲第一个共和国，推动民主共和观念深入人心。',
    side: Side.KMT,
    era: Era.OLD_DEMOCRATIC,
    isMajor: true,
  },
  {
    id: '1912-yuan-shikai',
    year: '1912',
    dateStr: '1912.3',
    title: '袁世凯窃国',
    description: '袁世凯窃取辛亥革命果实，建立北洋军阀统治，中国社会陷入新的政治黑暗。',
    people: '袁世凯',
    meaning: '表明旧民主主义革命未能完成反帝反封建的历史任务。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1912-warlord-era',
    year: '1912-1928',
    dateStr: '1912-1928',
    title: '军阀混战',
    description: '辛亥革命后北洋军阀与各地势力长期混战，中央政权更迭频繁，社会秩序混乱。',
    people: '北洋军阀各派',
    meaning: '凸显旧民主主义革命不彻底，反帝反封建任务未完成，为新的革命高潮孕育条件。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },
  {
    id: '1915-new-culture',
    year: '1915',
    dateStr: '1915.9',
    title: '新文化运动',
    description: '以《新青年》为主要阵地，提倡民主与科学，批判封建礼教，推动思想启蒙与文化更新。',
    people: '陈独秀、胡适、鲁迅',
    meaning: '为马克思主义传播和新民主主义革命奠定重要思想基础。',
    side: Side.OTHER,
    era: Era.OLD_DEMOCRATIC,
  },

  {
    id: '1919-may-fourth',
    year: '1919',
    dateStr: '1919.5',
    title: '五四运动',
    description: '由巴黎和会外交失败引发，全国爆发反帝反封建爱国运动，青年学生和工人阶级走到历史前台。',
    people: '李大钊、陈独秀、青年学生',
    meaning: '标志着中国新民主主义革命的开端。',
    side: Side.JOINT,
    era: Era.NATIONAL_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1921-cpc-founded',
    year: '1921',
    dateStr: '1921.7',
    title: '中国共产党成立',
    description: '中共一大在上海和嘉兴南湖召开，中国共产党正式成立，中国革命从此有了坚强领导核心。',
    people: '毛泽东、董必武、李达',
    meaning: '开天辟地的大事变，中国革命面貌焕然一新。',
    side: Side.CCP,
    era: Era.NATIONAL_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1924-kmt-first-congress',
    year: '1924',
    dateStr: '1924.1',
    title: '国民党一大',
    description: '国民党一大召开，联俄、联共、扶助农工三大政策提出，革命统一战线正式建立。',
    people: '孙中山、李大钊',
    meaning: '为国民革命高潮和北伐战争奠定组织基础。',
    side: Side.JOINT,
    era: Era.NATIONAL_REVOLUTION,
  },
  {
    id: '1925-may-thirtieth',
    year: '1925',
    dateStr: '1925.5',
    title: '五卅运动',
    description: '上海工人和学生因帝国主义枪杀工人而掀起大罢工、大游行，全国掀起反帝浪潮。',
    people: '上海工人、学生、工商界',
    meaning: '掀起国民革命高潮的重要导火索，推动全国反帝反封建斗争。',
    side: Side.JOINT,
    era: Era.NATIONAL_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1924-anti-imperial-feudal',
    year: '1924',
    dateStr: '1924',
    title: '反帝反封建斗争',
    description: '第一次国共合作后，工人、农民、学生运动高涨，各地展开反帝反封建的群众斗争，为北伐奠定群众基础。',
    people: '工人运动、农民运动骨干',
    meaning: '群众运动的蓬勃兴起为国民革命时期提供了广泛的群众动员力量。',
    side: Side.JOINT,
    era: Era.NATIONAL_REVOLUTION,
  },
  {
    id: '1926-northern-expedition',
    year: '1926-1927',
    dateStr: '1926.7',
    title: '北伐战争',
    description: '国共合作推动北伐，革命力量迅速向长江流域推进，沉重打击北洋军阀统治。',
    people: '蒋介石、周恩来',
    meaning: '推动全国革命形势迅速高涨。',
    side: Side.JOINT,
    era: Era.NATIONAL_REVOLUTION,
  },
  {
    id: '1927-412',
    year: '1927',
    dateStr: '1927.4',
    title: '四一二反革命政变',
    description: '蒋介石在上海发动反革命政变，大肆屠杀共产党人和革命群众，第一次国共合作破裂。',
    people: '蒋介石',
    meaning: '国民革命失败，中国革命进入土地革命战争新阶段。',
    side: Side.KMT,
    era: Era.NATIONAL_REVOLUTION,
    isMajor: true,
  },

  {
    id: '1927-nanchang',
    year: '1927',
    dateStr: '1927.8',
    title: '南昌起义',
    description: '中国共产党领导武装起义，打响了武装反抗国民党反动派的第一枪。',
    people: '周恩来、贺龙、朱德',
    meaning: '标志着中国共产党独立领导革命战争和创建人民军队的开始。',
    side: Side.CCP,
    era: Era.LAND_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1927-autumn-harvest',
    year: '1927',
    dateStr: '1927.9',
    title: '秋收起义',
    description: '毛泽东领导秋收起义后转兵井冈山，开辟农村包围城市、武装夺取政权的新道路。',
    people: '毛泽东',
    meaning: '推动中国革命战略方向发生根本转变。',
    side: Side.CCP,
    era: Era.LAND_REVOLUTION,
  },
  {
    id: '1928-jinggangshan',
    year: '1928',
    dateStr: '1928.4',
    title: '井冈山会师',
    description: '朱德、陈毅率部与毛泽东会师井冈山，红军主力开始形成。',
    people: '毛泽东、朱德、陈毅',
    meaning: '巩固了第一块农村革命根据地和人民军队骨干力量。',
    side: Side.CCP,
    era: Era.LAND_REVOLUTION,
  },
  {
    id: '1929-gutian',
    year: '1929',
    dateStr: '1929.12',
    title: '古田会议',
    description: '古田会议确立思想建党、政治建军原则，明确了党对军队绝对领导。',
    people: '毛泽东、朱德',
    meaning: '成为人民军队建设的重要里程碑。',
    side: Side.CCP,
    era: Era.LAND_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1931-918',
    year: '1931',
    dateStr: '1931.9',
    title: '九一八事变',
    description: '日本制造九一八事变并侵占中国东北，民族危机迅速加深。',
    people: '日本关东军',
    meaning: '揭开了日本全面侵华的序幕。',
    side: Side.JAPAN,
    era: Era.LAND_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1934-long-march',
    year: '1934-1936',
    dateStr: '1934.10',
    title: '红军长征',
    description: '中央红军因第五次反“围剿”失利被迫战略转移，历经艰险，最终完成伟大长征。',
    people: '毛泽东、周恩来、朱德',
    meaning: '保存了革命力量，锻造了中国革命走向胜利的骨干。',
    side: Side.CCP,
    era: Era.LAND_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1935-zunyi',
    year: '1935',
    dateStr: '1935.1',
    title: '遵义会议',
    description: '遵义会议在危急关头确立以毛泽东为代表的正确领导，中国共产党开始走向成熟。',
    people: '毛泽东、周恩来、张闻天',
    meaning: '是中国共产党历史上生死攸关的转折点。',
    side: Side.CCP,
    era: Era.LAND_REVOLUTION,
    isMajor: true,
  },
  {
    id: '1936-xian-incident',
    year: '1936',
    dateStr: '1936.12',
    title: '西安事变和平解决',
    description: '张学良、杨虎城发动兵谏，在中国共产党努力下西安事变得到和平解决。',
    people: '张学良、杨虎城、周恩来',
    meaning: '十年内战基本结束，抗日民族统一战线初步形成。',
    side: Side.JOINT,
    era: Era.LAND_REVOLUTION,
    isMajor: true,
  },

  {
    id: '1937-lugou',
    year: '1937',
    dateStr: '1937.7',
    title: '七七事变',
    description: '日军进攻卢沟桥，中国军民奋起抵抗，全国抗战全面爆发。',
    people: '中国守军、全国军民',
    meaning: '中国进入全民族抗战阶段。',
    side: Side.JOINT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1937-songhu',
    year: '1937',
    dateStr: '1937.8',
    title: '淞沪会战',
    description: '中国军队在上海地区顽强抗战数月，打破日军速胜幻想。',
    people: '张治中、陈诚',
    meaning: '迫使日本陷入长期战争，为全国抗战赢得时间。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1937-pingxingguan',
    year: '1937',
    dateStr: '1937.9',
    title: '平型关大捷',
    description: '八路军在平型关伏击日军，取得全面抗战以来的重要胜利。',
    people: '林彪、聂荣臻',
    meaning: '打破日军不可战胜神话，极大鼓舞全国抗战信心。',
    side: Side.CCP,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1938-taierzhuang',
    year: '1938',
    dateStr: '1938.3',
    title: '台儿庄大捷',
    description: '中国军队在台儿庄地区重创日军，取得正面战场重要胜利。',
    people: '李宗仁、孙连仲',
    meaning: '振奋全国士气，显示中华民族顽强抗战决心。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1940-hundred-regiments',
    year: '1940',
    dateStr: '1940.8',
    title: '百团大战',
    description: '八路军主动出击华北日军交通线和据点，大幅破坏敌后控制体系。',
    people: '彭德怀、左权',
    meaning: '扩大了敌后抗日根据地和中国共产党影响力。',
    side: Side.CCP,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1945-japan-surrender',
    year: '1945',
    dateStr: '1945.9',
    title: '日本投降书签字',
    description: '日本宣布无条件投降并正式签署投降书，中国人民抗日战争取得伟大胜利。',
    people: '中国军民',
    meaning: '中华民族近代以来反抗外来侵略第一次取得完全胜利。',
    side: Side.JOINT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },

  {
    id: '1945-double-tenth',
    year: '1945',
    dateStr: '1945.10',
    title: '双十协定',
    description: '国共重庆谈判结束，签署《双十协定》，社会各界普遍期待和平建国。',
    people: '毛泽东、蒋介石、周恩来',
    meaning: '中共赢得政治主动，也揭示了国内两种命运的激烈较量。',
    side: Side.JOINT,
    era: Era.LIBERATION,
  },
  {
    id: '1946-zhongyuan',
    year: '1946',
    dateStr: '1946.6',
    title: '中原突围与全面内战爆发',
    description: '国民党大举进攻解放区，中原突围打响，全面内战由此爆发。',
    people: '李先念、王震',
    meaning: '解放战争正式开始，双方进入全国性战略较量。',
    side: Side.CCP,
    era: Era.LIBERATION,
  },
  {
    id: '1947-dabie',
    year: '1947',
    dateStr: '1947.6',
    title: '刘邓大军挺进大别山',
    description: '人民解放军转入战略进攻，中原成为新的主要战场。',
    people: '刘伯承、邓小平',
    meaning: '揭开全国解放战争战略反攻序幕。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1948-liaoshen',
    year: '1948',
    dateStr: '1948.9',
    title: '辽沈战役',
    description: '东北野战军歼灭国民党主力，东北全境解放。',
    people: '林彪、罗荣桓',
    meaning: '三大战役的开端，解放战争形势开始发生决定性变化。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1948-huaihai',
    year: '1948',
    dateStr: '1948.11',
    title: '淮海战役',
    description: '中原和华东战场主力协同作战，歼灭国民党大量精锐部队。',
    people: '刘伯承、陈毅、粟裕、邓小平',
    meaning: '国民党主力基本被摧毁，长江以北大局已定。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1948-pingjin',
    year: '1948-1949',
    dateStr: '1948.11',
    title: '平津战役',
    description: '华北决战取得胜利，北平和平解放，华北全境获得解放。',
    people: '林彪、聂荣臻、罗荣桓',
    meaning: '三大战役完成，全国胜利已成定局。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1949-crossing-yangtze',
    year: '1949',
    dateStr: '1949.4',
    title: '渡江战役',
    description: '人民解放军百万雄师过大江，迅速解放南京、上海等重镇。',
    people: '邓小平、刘伯承、陈毅',
    meaning: '国民党政权统治中心瓦解，全国胜利加速到来。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1949-prc',
    year: '1949',
    dateStr: '1949.10',
    title: '中华人民共和国成立',
    description: '中央人民政府宣告成立，中国人民从此站立起来。',
    people: '毛泽东、周恩来、朱德',
    meaning: '中国新民主主义革命取得全国性胜利，历史进入新纪元。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },

  {
    id: '1950-volunteers',
    year: '1950',
    dateStr: '1950.10',
    title: '中国人民志愿军入朝作战',
    description: '志愿军跨过鸭绿江，开展抗美援朝、保家卫国战争。',
    people: '彭德怀、毛泽东',
    meaning: '新中国以实际行动捍卫国家安全和国际正义。',
    side: Side.CCP,
    era: Era.KOREAN,
    isMajor: true,
  },
  {
    id: '1952-shangganling',
    year: '1952',
    dateStr: '1952.10',
    title: '上甘岭战役',
    description: '志愿军在极端艰苦条件下坚守阵地，粉碎对手攻势，成为抗美援朝代表性战役。',
    people: '中国人民志愿军',
    meaning: '集中体现了中国军队顽强意志和战略定力。',
    side: Side.CCP,
    era: Era.KOREAN,
  },
  {
    id: '1953-armistice',
    year: '1953',
    dateStr: '1953.7',
    title: '停战协定签订',
    description: '板门店停战协定签字，抗美援朝战争取得伟大胜利。',
    people: '中国人民志愿军、朝鲜人民军',
    meaning: '新中国国际地位显著提升，边疆安全得到有力保障。',
    side: Side.CCP,
    era: Era.KOREAN,
    isMajor: true,
  },

  {
    id: '1950-land-reform-law',
    year: '1950',
    dateStr: '1950.6',
    title: '《中华人民共和国土地改革法》颁布',
    description: '新中国在广大新解放区开展土地改革，废除封建地主土地所有制。',
    people: '中央人民政府',
    meaning: '为农业恢复、社会稳定和国家工业化奠定基础。',
    side: Side.CCP,
    era: Era.SOCIALIST,
  },
  {
    id: '1953-first-five-year-plan',
    year: '1953',
    dateStr: '1953.1',
    title: '第一个五年计划开始实施',
    description: '国家集中力量发展重工业，推进社会主义工业化建设。',
    people: '中央人民政府',
    meaning: '标志着社会主义工业化建设全面起步。',
    side: Side.CCP,
    era: Era.SOCIALIST,
  },
  {
    id: '1954-constitution',
    year: '1954',
    dateStr: '1954.9',
    title: '第一届全国人大与宪法颁布',
    description: '第一届全国人民代表大会召开并通过《中华人民共和国宪法》，国家制度建设走向规范化。',
    people: '第一届全国人大代表',
    meaning: '人民代表大会制度正式确立，社会主义国家政权建设迈出关键一步。',
    side: Side.CCP,
    era: Era.SOCIALIST,
  },
  {
    id: '1956-socialist-transformation',
    year: '1956',
    dateStr: '1956.12',
    title: '社会主义改造基本完成',
    description: '农业、手工业和资本主义工商业的社会主义改造基本完成，社会主义制度在中国初步建立。',
    people: '全国人民',
    meaning: '中国从新民主主义社会进入社会主义社会。',
    side: Side.CCP,
    era: Era.SOCIALIST,
    isMajor: true,
  },
];
