import { Era, HistoricalEvent, Side } from './types';

export const EVENTS: HistoricalEvent[] = [
  // --- Anti-Japanese War ---
  {
    id: '1931-9-18',
    year: '1931',
    dateStr: '1931.9',
    title: '九一八事变',
    description: '日本侵占东北三省，国民政府实行不抵抗政策，民族危机全面爆发。',
    side: Side.JAPAN,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1932-1-28',
    year: '1932',
    dateStr: '1932.1',
    title: '一·二八淞沪抗战',
    description: '十九路军蔡廷锴坚守一个多月，民众抗日情绪高涨。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1933-3',
    year: '1933',
    dateStr: '1933.3',
    title: '长城抗战',
    description: '《塘沽协定》签订，华北危局加深。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1937-7-7',
    year: '1937',
    dateStr: '1937.7',
    title: '七七卢沟桥事变',
    description: '全面抗战爆发，国共第二次合作形成，全国动员抗战。',
    side: Side.JOINT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1937-9',
    year: '1937',
    dateStr: '1937.9',
    title: '平型关大捷',
    description: '林彪、聂荣臻指挥八路军取得首捷，打破日军不可战胜神话。',
    side: Side.CCP,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1937-8-11',
    year: '1937',
    dateStr: '1937.8-11',
    title: '淞沪会战',
    description: '国军顽强抵抗三月，战略转移至内地。战斗最惨烈，三个月灭亡中国计划破产。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1937-12',
    year: '1937',
    dateStr: '1937.12',
    title: '南京保卫战',
    description: '战败后爆发南京大屠杀，暴露日军残暴。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1938-3',
    year: '1938',
    dateStr: '1938.3-5',
    title: '台儿庄大捷',
    description: '李宗仁、张自忠指挥。抗战以来国军正面战场首次大规模歼敌胜利。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1938-6',
    year: '1938',
    dateStr: '1938.6-10',
    title: '武汉会战',
    description: '粉碎日军“速战速决”美梦，中国战场转入战略相持阶段。',
    side: Side.JOINT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1939-1942',
    year: '1939-42',
    dateStr: '1939-1942',
    title: '长沙会战三次',
    description: '粉碎日军速战速决幻想。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1940-8',
    year: '1940',
    dateStr: '1940.8-12',
    title: '百团大战',
    description: '彭德怀、左权指挥八路军主动出击华北，扩大共产党影响力。',
    side: Side.CCP,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },
  {
    id: '1944-4',
    year: '1944',
    dateStr: '1944.4-12',
    title: '豫湘桂会战',
    description: '国军惨重失利，抗战形势艰难。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1945-4',
    year: '1945',
    dateStr: '1945.4-8',
    title: '湘西会战',
    description: '薛岳指挥，抗战收官，中国取得胜利。',
    side: Side.KMT,
    era: Era.ANTI_JAPAN,
  },
  {
    id: '1945-8-15',
    year: '1945',
    dateStr: '1945.8.15',
    title: '日本宣布无条件投降',
    description: '中国人民抗日战争胜利，成为世界反法西斯战争主要战胜国。',
    side: Side.JOINT,
    era: Era.ANTI_JAPAN,
    isMajor: true,
  },

  // --- Liberation War ---
  {
    id: '1945-8',
    year: '1945',
    dateStr: '1945.8-11',
    title: '东北争夺战',
    description: '国共为控制东北展开政治与军事角力，中共逐步掌握主导。',
    side: Side.CCP,
    era: Era.LIBERATION,
  },
  {
    id: '1946-7',
    year: '1946',
    dateStr: '1946.7-9',
    title: '中原突围',
    description: '李先念指挥解放军保存主力，揭开全面内战序幕。',
    side: Side.CCP,
    era: Era.LIBERATION,
  },
  {
    id: '1947-3',
    year: '1947',
    dateStr: '1947.3-7',
    title: '陕北保卫战',
    description: '彭德怀指挥，中共中央安全转移，保存西北根据地。',
    side: Side.CCP,
    era: Era.LIBERATION,
  },
  {
    id: '1947-6',
    year: '1947',
    dateStr: '1947.6-9',
    title: '挺进大别山',
    description: '刘邓大军战略反攻开始，中原成为新战场。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1948-3',
    year: '1948',
    dateStr: '1948.3-5',
    title: '临汾战役',
    description: '晋南重镇解放，阎锡山势力削弱。',
    side: Side.CCP,
    era: Era.LIBERATION,
  },
  {
    id: '1948-9',
    year: '1948',
    dateStr: '1948.9-11',
    title: '辽沈战役',
    description: '林彪指挥，解放东北，歼敌47万，战争大转折。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1948-11',
    year: '1948',
    dateStr: '1948.11-1949.1',
    title: '淮海战役',
    description: '刘伯承、陈毅、邓小平、粟裕指挥，歼敌55万，国民党精锐全军覆没。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1948-12',
    year: '1948',
    dateStr: '1948.11-1949.1',
    title: '平津战役',
    description: '林彪、聂荣臻指挥，解放平津，华北全境归解放军。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1949-4',
    year: '1949',
    dateStr: '1949.4-6',
    title: '渡江战役',
    description: '百万雄师过大江，南京政府覆灭。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },
  {
    id: '1949-10-1',
    year: '1949',
    dateStr: '1949.10.1',
    title: '新中国成立',
    description: '中华人民共和成立，中国人民翻身做主，革命彻底胜利。',
    side: Side.CCP,
    era: Era.LIBERATION,
    isMajor: true,
  },

  // --- Korean War ---
  {
    id: '1950-6',
    year: '1950',
    dateStr: '1950.6',
    title: '朝鲜战争爆发',
    description: '美国主导的“联合国军”越过三八线，威胁中国边境安全。',
    side: Side.OTHER,
    era: Era.KOREAN,
  },
  {
    id: '1950-10',
    year: '1950',
    dateStr: '1950.10',
    title: '志愿军入朝',
    description: '彭德怀挂帅，以“抗美援朝、保家卫国”为口号，支援朝鲜。',
    side: Side.CCP,
    era: Era.KOREAN,
    isMajor: true,
  },
  {
    id: '1950-10-battles',
    year: '1950-51',
    dateStr: '1950.10-1951.6',
    title: '五次战役',
    description: '连续击退“联合国军”，奇袭云山，收复平壤，稳定战线于三八线。',
    side: Side.CCP,
    era: Era.KOREAN,
  },
  {
    id: '1951-1953',
    year: '1951-53',
    dateStr: '1951-1953',
    title: '相持阶段',
    description: '边打边谈，志愿军巩固阵地，国际声望大增。',
    side: Side.CCP,
    era: Era.KOREAN,
  },
  {
    id: '1953-7',
    year: '1953',
    dateStr: '1953.7.27',
    title: '朝鲜停战协定',
    description: '板门店签署。中国保卫了国家安全与边境稳定，确立了新中国国际地位。',
    side: Side.CCP,
    era: Era.KOREAN,
    isMajor: true,
  },
];